### ISSUE TITLE
No Developers Option 

### ISSUE THREAD

**Issue by Subas78** [833M0L3/NETTV#3]
There no option to enable usb debugging, and i tried it without that it says adb no connection could be made because the target machine actively refused it

**Comment by 833M0L3** [comment]
@Subas78 Could you share screenshots of the settings?

**Comment by Subas78** [comment]
Im sorry i totally forgot to tap for few times. It worked but i am having trouble to install apk. Is shows like this. 
![20230812_222039](https://github.com/833M0L3/NETTV/assets/142104275/48161f18-9404-41f6-89c7-6489a2bf35e1)
![20230812_222029](https://github.com/833M0L3/NETTV/assets/142104275/432fb07f-d2d4-4820-816c-51a9900be27c)

**Comment by Subas78** [comment]
![20230812_222039](https://github.com/833M0L3/NETTV/assets/142104275/0ac333ad-abcd-4a26-93af-205c34ab234c)

**Comment by Subas78** [comment]
Even though it shows your device is active i am not able to install that app
